### ISSUE TITLE
Prepare for 0.4.0 release

### ISSUE THREAD

**Issue by MathiasKoch** [BlackbirdHQ/atat#52]
I will do a 0.4.0 release to crates.io as soon as
- [x] [Make buffer length and queue lengths generic](#43) (PR: #50)
- [x] [Serialize and Deserialize tuple variants](#37) (PR: #51)
- [x] [Simplify and document releasing to crates.io](#47)

is fixed and merged into master.
